###############################################################
# Program:
#     Checkpoint 11b, Class Templates
#     Brother Dudley, CS165
# Author:
#     Will Brown
# Summary:
#     Summaries are not necessary for checkpoint assignments.
###############################################################


a.out : check11b.cpp pair.h
	g++ check11b.cpp
	tar -cf check11b.tar makefile *.h *.cpp

