###############################################################
# Program:
# Assignment 04, Product inventory
# Brother Dudley, CS165
# Author:
# Will Brown
# Summary:
# Put your summary code here... 
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

